#!/bin/bash

# quick-test-aurora.sh
# Prueba rápida de Aurora v370+ en producción
# 
# Uso: 
#   ./scripts/tests-manual/quick-test-aurora.sh

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 PRUEBA RÁPIDA: AURORA v370+"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 Envía estos mensajes desde WhatsApp al bot:"
echo ""
echo "1️⃣  Test: Saludo simple (NO debe decir 'Soy Aurora')"
echo "    📝 Mensaje: hola"
echo "    ✅ Esperado: '¡Hola! ¿En qué puedo ayudarte?' (SIN presentarse)"
echo ""
echo "2️⃣  Test: Pregunta sobre identidad"
echo "    📝 Mensaje: quien eres?"
echo "    ✅ Esperado: Respuesta completa sobre ecosistema Coworkia"
echo "    ✅ Debe incluir: 'torre de control', 'IA', 'sin llaves'"
echo ""
echo "3️⃣  Test: Pregunta sobre Coworkia"
echo "    📝 Mensaje: que es coworkia?"
echo "    ✅ Esperado: 'Coworkia es mucho más que un espacio...'"
echo "    ✅ Debe mencionar: ecosistema, empresas, comparaciones"
echo ""
echo "4️⃣  Test: Pregunta sobre servicios (NO debe presentarse)"
echo "    📝 Mensaje: que servicios tienen?"
echo "    ✅ Esperado: Lista directa de servicios (hot desk, salas)"
echo "    ❌ NO debe decir: 'Soy Aurora' o 'Mi nombre es...'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 CHECKLIST DE VERIFICACIÓN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "[ ] Aurora NO dice 'Soy Aurora' en saludos simples"
echo "[ ] Respuesta a 'quién eres' incluye metáfora torre de control"
echo "[ ] Menciona 'sin llaves físicas, sin recepcionista humana'"
echo "[ ] Incluye comparaciones IA vs humanos"
echo "[ ] Menciona compliance/UAFE en empresas"
echo "[ ] Tono confiado y persuasivo (no robótico)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 NOTAS:"
echo "  - Usuario de prueba: +593987770788"
echo "  - Heroku: coworkia-agent-e97d15dac56f.herokuapp.com"
echo "  - Versión actual: v371"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
